# File: docker-compose.yml
version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always

  nginx:
    image: nginx:stable-alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      # Volume để certbot xác thực (webroot)
      - ./certbot/www:/var/www/certbot 
      # Volume QUAN TRỌNG NHẤT cho SSL: chia sẻ thư mục chứng chỉ vào container
      - /etc/letsencrypt:/etc/letsencrypt:ro 
    depends_on:
      - frontend